#!yaml
name: Push to Docker registry

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Prepare Build Arg
        id: prepare_build_arg
        run: |
          echo "CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Build :latest
        if: success()
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/the_conclusion:${{ env.CURRENT_TAG }} .

      - name: Deploy :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKER_USERNAME }}/the_conclusion:${{ env.CURRENT_TAG }}
