#!yaml
name: Push to Docker registry

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Prepare Build Arg
        id: prepare_build_arg
        run: |
          if [[ ${GITHUB_REF#refs/tags/} =~ ^v[0-9]\.[0-9]\.[0-9] ]]; then
              echo "CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
          else
              echo "CURRENT_TAG=latest" >> "$GITHUB_ENV"
          fi

      - name: Build
        if: success()
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/the_conclusion:${{ env.CURRENT_TAG }} .

      - name: Deploy
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKER_USERNAME }}/the_conclusion:${{ env.CURRENT_TAG }}

      - name:  Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
  
      - name:  Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

#      - name: Build, tag, and push image to Amazon ECR
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
#        run: |
#          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.CURRENT_TAG }} .
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.CURRENT_TAG }}
#  
      - name: Debug
        run: | 
          echo ${{ steps.login-ecr.outputs.registry  }}
      - uses: docker/build-push-action@v2
        id: build-image
        with:
          push: true
          file: Dockerfile
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO_NAME }}:${{ env.CURRENT_TAG }}
  
