#!yaml
name: Push to Docker registry

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Common: Prepare Build Arg
        id: prepare_build_arg
        run: |
          if [[ ${GITHUB_REF#refs/tags/} =~ ^v[0-9]\.[0-9]\.[0-9] ]]; then
              echo "CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
          else
              echo "CURRENT_TAG=latest" >> "$GITHUB_ENV"
          fi

      - name: DockerHub: Build
        if: success()
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/the_conclusion:${{ env.CURRENT_TAG }} .

      - name: DockerHub: Deploy
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKER_USERNAME }}/the_conclusion:${{ env.CURRENT_TAG }}

      - name: Amazon ECR: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
  
      - name: Amazon ECR: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Amazon ECR: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY/the_conclusion:${{ env.CURRENT_TAG }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/the_conclusion:${{ env.CURRENT_TAG }}
          #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.CURRENT_TAG }} .
          #docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.CURRENT_TAG }}
